### ISSUE TITLE
snet  mpe-client call_server command does not fails during reported service error

### ISSUE THREAD

**Issue by stellarspot** [singnet/snet-cli#102]
I run the command where 'snet  mpe-client call_server' where some arguments are not correct.
Something like:
```snet  mpe-client call_server 0x5c7a4290f6f8ff64c69eeffdfafc8644a4ec3a4e 0 10 localhost:8080 "\"Addition"\" add '{"a":10,"b":32}'```

snet prints the error from the service but does not fail the process:
```
unspent_amount before call (None means that we cannot get it now):420000
Error: Critial Error. ""Addition"" is not an identifier
If you want to see full Traceback then run:
snet --print-traceback [parameters]
```

See for example CircleCI output: https://circleci.com/gh/stellarspot/platform-pipeline/91

**Comment by astroseger** [comment]
was done by #114
