### ISSUE TITLE
Refactor User Interaction

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#104]
There are several design choices for how service authors interact with the CLI that I think could be improved. Publishing a service requires individual steps and keeping track of a global state which results in having to track the agent address manually. See discussion on singnet/wiki#16

This is a proposal for a substantial refactor of the interface, but to only be worked on once the core SNet behaviour has been built and stabilized. Discussion is welcome!

## Local state

Instead of tracking config related to snet-cli globally, and dumping different json files in different locations, we should keep all SNet related files together.

e.g. inside a service directory, we could have a structure like:
- `.snet\service.json`
- `.snet\daemon.json`
- `.snet\[other?]` - should compiled protobuf files go here too?

The daemon and CLI could then read the information they need from this local context if it exists.

Motivation:
- the daemon wouldn't require a user to specify where the config file is, and the user wouldn't have to separately create it. All this information could be generated as part of creating a service.
- the `current_agent_at` and other `current_` state variables are not a useful pattern to service authors. It's hard to remember what the current identity, network, and agent address all are set to. All of these could be stored in `service.json` meaning the user doesn't have to remember anything... they just have to be in the right directory.

In addition, like `git`, if there is no `.snet` directory, our tools should walk to parent directories until a `.snet` directory is found and use that.

## Commands

Ideally, once a user has configured the CLI (with identity, network), then there should only be two core
commands. We could call these different things, but I think following git subcommand names will mean less cognitive demand of new users:

- `init` - create a new service in the current directory. This should also generate template proto files for the interface definition, unless they already exist. This doesn't push anything to blockchain or IPFS.
- `push` - this command should automagically figure out if it needs to create/modify contracts or publish changes to IPFS. So the first time you run it it will create a new agent - possibly with a warning/confirmation. Later it will only do something if you've changed the config somehow.

Beyond that, in the future I could see these to commands being useful:

- `run`/`develop`
    - First regenerate proto/grpc related code if proto files have changed.
    - Then run a local server (the command to run the user's service should be in the local config) and the SNet daemon. This removes the need for service authors to create their own scripts that launch and monitor these two processes.
    - `run` would provide a functional server that could be production ready (for simple services that don't have complex architecture)
    - `develop` would have additional debugging abilities, including hosting a webserver that would show a simple version of what the dapp provides. This would allow users to easily debug and test their UI layout locally.
- `deploy` - when we have SNet infrastructure, this would deploy the current service to our (or another) cloud service.

## Documentation and Metadata

There is a field in metadata for a description of the service. This is nice, but
it'd be great to make it really easy to publish markdown descriptions. These could then be rendered nicely in a dapp).

Rather than putting this documentation in a json value (urgh!!), we could allow the user to place it as a markdown file inside the services `.snet` directory. This would automatically be bundled and published to IPFS. Down the road we might want to allow more complex documentation structures e.g. an entire directory of documentation that can be fetched by service clients and browsed locally. If we want a decentralised developer network, then this is a better option than relying on github or other external websites for decent documentation.

## Summary

I know there is a lot of work before we get to this point, but I wanted to describe it here because I think aiming for a developer experience like this would make SNet really pleasant to use.

But please let me know if you think otherwise!

**Comment by astroseger** [comment]
Very soon (hope this Friday) many parts of snet-cli will be deprecated (with deprecation of old payment system).  
* "snet agent", "snet agent-factor" will be depricated
* "snet client" will be deprecated and replaced with "snet mpe-client"
* "snet service" will be deprecated and replaced with "snet mpe-service"
 
Both mpe-service and mpe-client are in active development now, so their interface have not been finalized yet. 

But after you feed back about possible refactoring will be very important.

**Comment by arturgontijo** [comment]
> "snet client" will be deprecated and replaced with "snet mpe-client"
> "snet service" will be deprecated and replaced with "snet mpe-service"

Is it possible to "update" the `snet client` to be the new `snet mpe-client`?
If so, I'd like to suggest this change. I think that the first one is much more clean than the second.

**Comment by astroseger** [comment]
snet mpe-client it is and update of snet client :) . It is based on snet client code (in terms of general architecture and grpc calls).

**Comment by pennachin** [comment]
I think @arturgontijo's point, which I agree, is that the commands should stay the same -- no reason to use `mpe-client` and `mpe-service` after deprecation.

**Comment by astroseger** [comment]
Should we close it?

**Comment by ferrouswheel** [comment]
I'm only just catching up after being on leave, do you know which changes are related to this issue?

I know you've improved a bunch of the snet-cli commands already...

However, I also think grouping the daemon and service config files into an `.snet/*` directory and making them consistent with each other is important long term.

As is having simple start up commands like `run`/`develop` so people don't have to worry about process management of snetd and their server.

But those could be long term goals, and perhaps this issue should be broken up into specific proposals that can be decided on individually?

**Comment by ferrouswheel** [comment]
As proposed, I have made issues for each proposal in this document.
