### ISSUE TITLE
snet organization create does not print error message

### ISSUE THREAD

**Issue by stellarspot** [singnet/snet-cli#119]
I started IPFS, migrated contracts and run ganache-cli.
When I call 'snet organization create' it prints nothing as it passed, but it really fails without any error message:

```
snet organization create TestOrg  -y 
echo $?
1
```

**Comment by astroseger** [comment]
@stellarspot  could you check it again in your environment? It might be solved in #136

**Comment by astroseger** [comment]
closed with #142
