### ISSUE TITLE
snet identity should print options, not the list identies (the same for snet networks)

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-cli#131]
In the current implementation ```snet identity``` prints list of identities. Which is a little bit confusing (because other commands actually print list of options).
```snet identity``` should print list of options, and we should have separate function, for example ```snet identity list``` to print list of identities. 

@arturgontijo @ferrouswheel   do you agree?

**Comment by ferrouswheel** [comment]
If it makes things consistent that makes sense.

**Comment by astroseger** [comment]
closed with #136
