### ISSUE TITLE
Shoud we keep or remove possibility to define --eth-rpc-endpoint from the command line?

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-cli#137]
In the current version there is a possibility to set eth-rpc-endpoint from command line. 

It means that you can call other network from session enviroment of another network. For example your current network is "mainnet", but your can run "kovan" without switching to kovan.

Why would you want it? In most cases it will work, but it kind of break all logic. For example in your configuration file you could have different default_gas_price in different networks....

Or there are some situation in which you might want to use different rpc endpoints for the same network?

**Comment by arturgontijo** [comment]
IMO this flag doesn't make sense with the new `network` command logic.

**Comment by astroseger** [comment]
So I will remove --eth-rpc-endpoint already in #136

**Comment by astroseger** [comment]
In #136 we will:
1. Remove --eth-rpc-endpoint command line option
2. Add possibility to change default_eth_rpc_endpoint in configuration file by using "set default_eth_rpc_endpoint"

I'm also hesitating to rename "default_eth_rpc_endpoint" in configuration file to simply "eth_rpc_endpoint", because now it is only one source of eth_rpc_endpoint not the default one. However in future we could have some situation with multiply eth endpoints for the same network thought....

**Comment by astroseger** [comment]
Ok I leave default_eth_rpc_endpoint for now... as well as default_ipfs_endpoint. 
closed with #136

**Comment by ferrouswheel** [comment]
So I ran into an issue where changing my network with `snet network kovan` didn't update my session's `default_eth_rpc_endpoint`. I expected it would change my `eth_rpc_endpoint` to the one that the network config had:

```
[network.kovan]
default_eth_rpc_endpoint = https://kovan.infura.io
default_gas_price = 1000000000

...other networks

[ipfs]
default_ipfs_endpoint = http://ipfs.singularitynet.io:80

[session]
network = kovan
identity = joel
default_eth_rpc_endpoint = http://127.0.0.1:1234
...
```

I think that if changing network won't update `default_eth_rpc_endpoint` in session, then it should be renamed `custom_eth_rpc_endpoint`, `force_eth_rpc_endpoint`, or `override_eth_rpc_endpoint`.

**Comment by astroseger** [comment]
How did you get default_eth_rpc_endpoint into your [session] field? It shouldn't be here.
When you call "snet set default_eth_rpc_endpoint" it changes it for the current network... So it should be impossible to have default_eth_rpc_endpoint in the session fields (because it belongs to network fields)....

**Comment by ferrouswheel** [comment]
Ah I see - it was probably just left over from a prior version of snet-cli then. I deleted it and things are fine now.
