### ISSUE TITLE
Add command to download service API protobuf file

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#149]
In cases when client uses `snet-cli` to call the service which was not used before, it is required to get the API first to see methods and input/output data structures to form correct `snet-cli call`. At the moment there is no command in `snet-cli` to do such thing. It's worth to add this command for people who discovers services via `snet-cli`.

For instance: `snet-cli service get_api <folder>` to download and unpack protobuf API description into folder.

**Comment by astroseger** [comment]
I've added two commands in #148 :
* ```snet service  get_api_metadata```  - extract protodir with given metadata file
* ```snet service  get_api_metadata``` - extract protodir with given orgid and servid

**Comment by ksridharbabuus** [comment]
We generally enable Swagger in most of the APIs we expose. We need to get the similar approach to our services as well for developers to get their hands dirty.

**Comment by astroseger** [comment]
was closed in #148
