### ISSUE TITLE
More accurately work with stdout and stderr

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#153]
`snet-cli` sometimes shows errors at `stderr` and sometimes at `stdout`. One of the examples is a `open_init_channel_registry` command which shows few warnings about 'IPFS hash checking' sometimes via stdout and sometimes via stderr. It makes it difficult to parse command output automatically.

**Comment by vsbogd** [comment]
Adding @edguy3 who raised it at the workshop

**Comment by astroseger** [comment]
I believe it was close with #148
