### ISSUE TITLE
snet-cli lacks method for updating proto file in ipfs

### ISSUE THREAD

**Issue by noskill** [singnet/snet-cli#166]
currently there 2 ways to update api:
1) generate new metadata with ```snet service metadata-init```
but it will change group id making all channels invalid
2) put tar with proto file into ipfs manually and manually update hash in metadata file and call  ```snet service update-metadata```

**Comment by astroseger** [comment]
Will be fixed in #170 

If service provider need to update protobuf model he can do the following:
```
# Get current service metadata
snet service  print-metadata  <org_id> <service_id> >  service_metadata.json

# Update protobuf model in ipfs and update service metadata file 
snet service metadata-set-model <new_protobuf_dir>

# Update metadata in the registry 
snet service update-metadata
```
