### ISSUE TITLE
Validate endpoint is a URL

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#172]
Service endpoints don't get validated:

`snet service metadata-add-endpoints blah`
`snet service metadata-add-endpoints 'blah*&^%$#'`

Both the above are accepted and added to the metadata json.

This was raised in #49, then fixed in #60. Then later in #87 we suggest swapping to `urllib.parse` to avoid calling the url unnecessarily.

The MPE implementation doesn't do any checking.

**Comment by astroseger** [comment]
It is related to https://github.com/singnet/snet-daemon/issues/153  and partly duplicate https://github.com/singnet/snet-cli/issues/127 . 
Let's discuss in  https://github.com/singnet/snet-daemon/issues/153 .
