### ISSUE TITLE
--fixed-price argument for "snet service metadata-init" does not work

### ISSUE THREAD

**Issue by ramongduraes** [singnet/snet-cli#195]
Hey, it looks like a simple bug but I've just initialized a service metadata using `snet service metadata-init service/service_spec/ SERVICE_ID WALLET_ADDRESS --endpoints http://IP:PORT --fixed-price 0 --service-type process --encoding json` and the resulting **service_metadata.json** has `"pricing": {},`. 

I've tried going all the way and published the service anyway, but when I called it I got `Error: 'price_model'`. Have a look into that please!

**Comment by astroseger** [comment]
yes... it is a bug... ```--fixed-price``` doesn't work for zero price. I will fix it.
