### ISSUE TITLE
Change version number when something changes

### ISSUE THREAD

**Issue by ramongduraes** [singnet/snet-cli#196]
Running `snet version` is the best way to keep track of our installed version vs the latest release. However, SNET CLI has been changing quite a bit but the version numbers do not indicate that. 

For instance, my colleagues and I all had snet-cli version 0.1.9 installed but only one of us had `snet service metadata-set-model` command available. After pulling the repository and reinstalling it everything worked. Since we're using the MAJOR.MINOR.PATCH versioning system, the patch number could've changed to 0.1.10 to indicate that something has changed.

**Comment by ramongduraes** [comment]
Adding build number to `snet version` is also an option

**Comment by ferrouswheel** [comment]
The MAJOR.MINOR.PATCH of `snet version` shouldn't change until there is a packaged release.

However automatically adding the git hash to versions installed directly from the repo would be a sensible way to indicate development versions are different.

**Comment by prashantramangupta** [comment]
@astroseger @raamb 
1. we should have version.py in our package, from where we will read the version in setup.py. Currently, we are reading from __init__.py
2. code build will write a version in version.py during the build
https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package

**Comment by raamb** [comment]
@vinthedark now that pr #237 has been merged, lets update the client CD to set the version number in the build, similar to what we did on the daemon.

**Comment by vinthedark** [comment]
Setting up the version number as a part of the CD is been taken care. Going forward, the version number will be updated during every github release.
