### ISSUE TITLE
Call service with 'org_id + service_id + method_name' not whit 'channel_id + method'

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-cli#201]
In the current version ```snet client call``` has the following parameters: ```channel_id, price, endpoint, method, params```.
It might be more convenient for users to have the following parameters: ```price, org_id, service_id, method```.  
* we could remove ```price```. But we probably should keep it for cross check.
* ```endpoint``` could be made optional. By default, we read endpoint from metadata and use round-robin in case of multiply endpoints
* ```channel_id``` is optional. We need it only in case we have several initialized channel for the same service. 

To implement it, we need to have a way to find all initialized channels which was open for specific service. We already have it  (see ```MPEChannelCommand.print_initialized_channels_filter_group```). However it might be not the fastest way (in case of many initilized channels). But I guess it is fast enough for now...

**Comment by ferrouswheel** [comment]
Please make it possible to do `snet client call ORG SERVICE_NAME METHOD_NAME`.

Don't require price, if no price is specified you can ask the user to confirm, but it's really frustrating to have to look it up.

**Comment by astroseger** [comment]
Should user specify the price? It is a question.
I prefer that user specify the price, because otherwise he can be attacked by malicious service provider.

**Comment by ferrouswheel** [comment]
The CLI can always ask for the user to confirm they are okay with the current price.

Currently I have to look up the price in the `service_metadata.json` and it's frustrating to remember (especially because I have to covert between cogs and AGI).

**Comment by arturgontijo** [comment]
Remove price would be nice (with prompt price value question, like"The service's price is 10 COGs, proceed?") and keep the `--yes` to avoid this if wanted.

**Comment by astroseger** [comment]
was closed by #210
