### ISSUE TITLE
How to find out what service a channel belongs to

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#203]
I'm not sure if there is another command I can use, but if I want to find out what service is associated with a channel I currently have to look at all my `service_metadata.json` files and try to find a matching group id.

Even if the information isn't available on the blockchain, snet cli could maybe store a mapping locally when the channel is created?

```
$ snet channel print-initialized
#channelId nonce recipient groupId(base64) value(AGI) expiration(blocks)
49 1 0x464c564e427fA7A715922D9E0373a5D90589E021 cKQBPXqInGo3BDSBGEi2oXjiX4hpjKJ50aBEvC7dxeg= 0.000001 10284000
```

**Comment by astroseger** [comment]
There is a command for it:
```snet channel print-initialized-filter-group```
and after we implement #201 it will not be necessary at all (but I will be able to do it only next week :( )

**Comment by ferrouswheel** [comment]
Thanks - that's the command I needed :+1:

Would eventually be nice to have the main list of channels annotated with service id, but this works for now :-)

**Comment by astroseger** [comment]
Yes. it will be part of #201: ```snet channels print-initialized``` will print list of channels with org_id+service_id.

**Comment by astroseger** [comment]
so we could close this issue for now...

**Comment by ferrouswheel** [comment]
:+1:
