### ISSUE TITLE
Support domain name based services from snet-cli

### ISSUE THREAD

**Issue by raamb** [singnet/snet-cli#208]
The client only allows service calls to ip:port. This is a problem if a daemon uses a domain name. One scenario is if a daemon is getting its SSL certificates from LetsEncrypt using a domain name.

**Comment by ferrouswheel** [comment]
As far as I can tell there is nothing that explicitly prevents using a domain name. What version are you using and what is the error you are getting?

**Comment by raamb** [comment]
Current snet-client does not do a name lookup per Sergey.

**Comment by ferrouswheel** [comment]
Why does snet-client need to do a name lookup?

Opening a grpc connection using a hostname should take care of that.

**Comment by astroseger** [comment]
Yes. It seems you are right, grpc should make hostname lookup by itself (https://grpc.io/grpc/core/md_doc_naming.html). Which raises some question about security... We really should start to use secure channels asap.

**Comment by astroseger** [comment]
was fixed by #210 (in general this issue was about support https...)
