### ISSUE TITLE
API description in README is out of sync with latest build.

### ISSUE THREAD

**Issue by TScottJ** [singnet/snet-cli#230]
Some of the snet service documentation in the README is out of sync with the latest build. For example, *snet service metadata_init* should be *snet service metadata-init* and the positional arguments are different. There may be a way to auto-generate these from the CLI somehow.

**Comment by raamb** [comment]
#234 updates the PR. We will auto generate this very soon

**Comment by raamb** [comment]
#248 fixes this.
