### ISSUE TITLE
grpcio-health-checking version is incompatible with grpcio-tools

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#243]
In setup.py

```
grpcio-health-checking==1.19.0
...
grpcio-tools==1.17.1
```

On running snet: `pkg_resources.DistributionNotFound: The 'grpcio>=1.19.0' distribution was not found and is required by grpcio-health-checking`

Fix is change `grpcio-tools==1.19.0`

**Comment by arturgontijo** [comment]
Just to point it out...

I think your installation has cached some of the modules, because pip should install `grpcio==1.19.0` for `grpcio-health-checking==1.19.0`.
Here, using a fresh virtualenv, it seems to working fine:
```
snet-cli$ pip install --ignore-installed --no-cache-dir -e .
...
snet-cli$ pip list
...
grpcio                 1.19.0        
grpcio-health-checking 1.19.0        
grpcio-tools           1.17.1
...
snet-cli$ snet --print-traceback service print-service-status snet example-service
    default_group:
    -   endpoint: https://bh.singularitynet.io:7052
        status: Available
```

But the PR makes sense! =)

**Comment by ferrouswheel** [comment]
yeah you're right, I just tried to update the existing virtualenv with `pip install -e .` so would explain why this wasn't picked up earlier by CI.
