### ISSUE TITLE
Unable to re publish services if any new images are added to the metadata 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-cli#329]
snet --print-traceback service metadata-add-assets hero_text-generation.jpg hero_image --metadata-file service_metadata.json

Error Seen 
_File error  Object decoding error: Expecting value: line 1 column 1 (char 0)_

**Comment by keshrisohit** [comment]
seems issue was with when pushing image of very large size.Please re-open if you face issue again
