### ISSUE TITLE
What is the purposes of the `daemon_addresses` service metadata field?

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#385]
`daemon_addresses` field was added into service metadata structure by PR https://github.com/singnet/snet-cli/pull/373

But I cannot find any documentation according this field. 
Could you please clarify answers to the following questions:
- what is daemon address?
- how it is going to be used?

**Comment by anandrgitnirman** [comment]
daemon adress is the Ethereum public address , this was introudcued to help say when Daemon wants to talk / send some information to a third party ( ex Metering stats) , the third party can know if the request came in from an Authentic Daemon , Deamon will have the pvt key associated to this address  and will sign using this pvt key when making any requests to other systems.

**Comment by vsbogd** [comment]
Thanks @anandrgitnirman !
