### ISSUE TITLE
What is the purpose of `org_type` field in organization metadata?

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-cli#386]
`org_type` field was added into organization metadata structure by PR https://github.com/singnet/snet-cli/pull/368

But I cannot find any documentation describing the purpose of the field. Could you please clarify how this field is going to be used?

**Comment by anandrgitnirman** [comment]
an organization can be created by anyone on block chain ,but to ensure KYC ( Know your client - or the indivudual ) or  KYB (Know your Organization / Business) , we introduced the type in organization metadata ,this field was introduced to highlight if the organization beloonged to an individual or a Business , @pratik-vii , pls updated the doumentation with these details

**Comment by vsbogd** [comment]
Thanks @anandrgitnirman :+1: so it doesn't affect any functionality yet but more about business processes.
