### ISSUE TITLE
Snet-cli still using deprecated Ethereum testnet "Ropsten" instead of latest available "Goerli" or "Sepolia" 

### ISSUE THREAD

**Issue by shafinshaikh** [singnet/snet-cli#463]
The CLI is using the deprecated Ethereum testnet Ropsten and the code should be migrated in order to use the testnet Goerli/Sepolia

**Comment by kiruxaspb** [comment]
In recent updates we added the Sepolia network 🎯, it will soon become mainstream as Goerli will soon be deprecated as well. Use only the latest version of the CLI to ensure stable work.
