### ISSUE TITLE
Error message is not printed when  service spec retrieving is failed

### ISSUE THREAD

**Issue by stellarspot** [singnet/snet-cli#53]
Steps to reproduce:
- Go to the example-service project
- Run in command line:
`snet service init`
- For the choice 'Choose the path to your service's spec directory: (default: "service_spec/")' type . (current directory, this allows to resolve the provided path)
- Use snet to publish the local config
-Run example-service with snet-daemon
- Execute  snet client call classify 

The error 'ERROR: failed to retrieve service spec' is not printed.

**Comment by arturgontijo** [comment]
I was able to reproduce this as well.
Maybe we could specify the folder in ERROR: message, what do you think?

Like: 'ERROR: failed to retrieve service spec files from . (or whatever user has specified at service init)'

**Comment by arturgontijo** [comment]
The folder specification with ERROR won't make sense for third party service...
If we pass `out_f=self.err_f, err_f=self.err_f,` at the get_spec() call, the message will be printed.
At [command.py:L510-L516](https://github.com/singnet/snet-cli/blob/master/snet_cli/commands.py#L510-L516)
