### ISSUE TITLE
Add deug level to print log messages.

### ISSUE THREAD

**Issue by stellarspot** [singnet/snet-cli#56]
See discussion: https://github.com/singnet/snet-cli/pull/55#discussion_r219825270

Current snet-cli implementation allows to print both log messages and errors into std err or nothing.
It would be useful to add a debug level so it allows to print only error messages or both error and log messages.

**Comment by astroseger** [comment]
Actually there is already 3 different "verbose" levels for transactions:
* by default
* --verbose or -v
* --quite or -q  (but it will be really quite only with '-y' options which makes sense)

So I would close this issue for now, and possible open new issue for adding proper logging.
