### ISSUE TITLE
Is the npm dependency necessary?

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#6]
From what I can tell, the node and npm dependency is only needed to copy the contract json files from the `singularitynet-alpha-blockchain` package.

Is there some tooling from node/npm that we want to use, or would a cleaner alternative be to use a python script to download the contract files from a tagged release on github?

My understanding is also that npm is only needed for `snet-cli` development as the contract json files get bundled in the python package. Thus most users won't need node installed and it could be removed from the documented requirements?

**Comment by lcdupree** [comment]
We need to improve the readme to make it clear for folks that they just need to "pip install snet-cli" to use the CLI without installing additional dependencies. Our readme is a little confusing about this distinction between a developer who wants to help improve our CLI (and the tools they need installed to do that) vs. a developer/user who wants to use the CLI to interact with the platform.

We have a separate longer-term question of how to dynamically pull resources (like contract ABIs, network addresses) onto a end-user's machine that we don't need to solve today. We currently package these resources on a 1:1 basis when we publish the CLI to PyPi.

We can close this issue after we improve the readme to better describe the development vs. end-user scenarios for the CLI.

**Comment by erickearns** [comment]
Reorganized README to have a "Development" section below the getting started that is intended for users of snet-cli.
