### ISSUE TITLE
Optionally tie identity to network

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#7]
As I understand, one *can* use the same identity on multiple networks, but from the view of good security practice I wouldn't want to be using my **mainnet** identity on **kovan**. It would be too easy to accidentally use real ETH instead of KETH.

Would it make sense to allow the user to specify a network when creating an identity? Then when that identity is selected, the correct network could automatically be updated for the current session.

You could still allow no network to be specified. In that case, when an identity with no network is selected, a warning could be shown. This would remind the user that they may want to change the network manually.

**Comment by astroseger** [comment]
I would propose that user should specify which identity he wants to use for network he is switching to.
for example
```
snet kovan kovan-user
snet mainnnet user2
```

**Comment by arturgontijo** [comment]
Maybe something like:
`snet identity create kovan kovan-user`?
And every time user selects this identity, `snet` automatically (re)set network to `kovan` (or to whatever the identity was bind to).

**Comment by astroseger** [comment]
@arturgontijo  it is slightly more difficult to implement. We also probably should have identities which are not bind to the network (as @ferrouswheel proposed originality)
So we should have something like this:
```
# bind to kovan
snet identity create kovan-user --network kovan
# free identity
snet identity create universal-user 
```

**Comment by arturgontijo** [comment]
>You could still allow no network to be specified. In that case, when an identity with no network is selected, a warning could be shown. This would remind the user that they may want to change the network manually.

This warning will be very important.

**Comment by astroseger** [comment]
Ok I will try to do it together with #110

**Comment by vsbogd** [comment]
As far as I understand your proposal is to add ```<identity>``` positional parameter to the ```snet network``` command. At the same time we have ```snet identity``` command. What is wrong with having them separate? One command does one thing if you need to do two things you can use two commands. This will make code simple and clear.
