### ISSUE TITLE
snet binary not compiling

### ISSUE THREAD

**Issue by theaayushanand** [singnet/snet-cli#79]
Hello I have tried building the snet binary from pip as well the source code but both time after installation i get the following error stack 
`root@aayush:~/singnet/src/github.com/singnet/snet-cli# snet
Traceback (most recent call last):
  File "/usr/local/bin/snet", line 11, in <module>
    load_entry_point('snet-cli', 'console_scripts', 'snet')()
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/__init__.py", line 11, in main
    parser = arguments.get_root_parser(conf)
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/arguments.py", line 42, in get_root_parser
    add_root_options(parser, config)
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/arguments.py", line 80, in add_root_options
    add_contract_options(contract_p)
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/arguments.py", line 235, in add_contract_options
    add_contract_function_options(contract_p, contract_name)
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/arguments.py", line 415, in add_contract_function_options
    for fn in filter(lambda e: e["type"] == "function", contract_def["abi"]):
  File "/root/singnet/src/github.com/singnet/snet-cli/snet_cli/arguments.py", line 415, in <lambda>
    for fn in filter(lambda e: e["type"] == "function", contract_def["abi"]):`
python version is 3.6.3. I am trying to setup on ubuntu 16, 64 bit.
Thanks for the help

**Comment by stellarspot** [comment]
There were some changes in platform-contracts which are necessary to build snet-cli from master branch.

Could you try to build platform-contracts first?
You can look ate steps used by  CircleCI script to build the snet-cli: 
https://github.com/singnet/snet-cli/blob/master/.circleci/config.yml

Build platform-contracts:
```
          git clone https://github.com/singnet/platform-contracts.git
          cd platform-contracts
          npm install
          npm run-script compile
          npm run-script package-npm 


```
Build platform-contracts:
```
          ./scripts/install_dev.py $SINGNET_REPOS/platform-contracts
          sudo pip3 install -e .
```

**Comment by vsbogd** [comment]
PR https://github.com/singnet/snet-cli/pull/80 should fix the issue it gets the latest platform contracts from github releases.

**Comment by theaayushanand** [comment]
Thanks it worked .

> There were some changes in platform-contracts which are necessary to build snet-cli from master branch.
> 
> Could you try to build platform-contracts first?
> You can look ate steps used by CircleCI script to build the snet-cli:
> https://github.com/singnet/snet-cli/blob/master/.circleci/config.yml
> 
> Build platform-contracts:
> 
> ```
>           git clone https://github.com/singnet/platform-contracts.git
>           cd platform-contracts
>           npm install
>           npm run-script compile
>           npm run-script package-npm 
> ```
> 
> Build platform-contracts:
> 
> ```
>           ./scripts/install_dev.py $SINGNET_REPOS/platform-contracts
>           sudo pip3 install -e .
> ```

**Comment by astroseger** [comment]
@theaayushanand  could you try without install_dev.py? Finally we've implemented better for installing contracts (#80), so I'm going to remove install_dev.py.

**Comment by theaayushanand** [comment]
@astroseger the error returns when i use "./scripts/blockchain install"

**Comment by astroseger** [comment]
@theaayushanand which error? #80 was merged few minutes ago. Have you made git pull?

**Comment by astroseger** [comment]
I'm going to remove install_dev.py with the next pull request. So please make sure that you don't need it anymore.

**Comment by theaayushanand** [comment]
sure i will test again and update here. probably i had not pulled the updated repos. Thanks for the response.

**Comment by astroseger** [comment]
Should we close it?

**Comment by theaayushanand** [comment]
yes works for me . thanks
