### ISSUE TITLE
service publish attempts to hit the service endpoint

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#87]
When we publish a service, we are given an agent address.

The address is used to configure the daemon.

So the daemon won't be running until after the service is published.

Thus hitting the endpoint during the publish command seems unnecessary (unless there is already a valid agent address, and publish is just updating the endpoint).

**Comment by vsbogd** [comment]
I agree with @ferrouswheel. Agent contract is going to be deprecated. However we plan using published information about service as a daemon configuration, so in general we cannot rely on fact that daemon is running before service is published.

**Comment by arturgontijo** [comment]
My idea when running this test was more to warn user about a possible mistyping on provided endpoint, like `httpp://127.0.0.1:7000`. So the user can check it again and confirm if it's really ok.
But I agree that's not the best way to do it, maybe we could use just `urllib.parse` (I also think @vsbogd suggested this at the beginning).

**Comment by ferrouswheel** [comment]
I couldn't find any logic in [publish](https://github.com/singnet/snet-cli/blob/master/snet_cli/mpe_service_command.py) which attempts to connect to the end point.

Unfortunately I couldn't find any validation that endpoint is a valid URL as suggested by @arturgontijo. But I'll make that a separate issue...
