### ISSUE TITLE
check hash of files from IPFS

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-cli#91]
We should check hash of files from IPFS. Otherwise we can be attacked if ipfs client is compromised.
Function which read IPFS is here:
https://github.com/singnet/snet-cli/blob/49c6dbaca8b8aace1bdd77dbc1f6c0ae0397d0f6/snet_cli/utils_ipfs.py#L27-L30

**Comment by ferrouswheel** [comment]
It is concerning for a first time user to see this warning as normal behaviour, so we should either fix this for the beta or at the least link to this github issue.
