### ISSUE TITLE
members list should be optional in 'snet organization create'

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-cli#93]
To create a personal org, I need to do:

> snet organization create joel MY_ADDRESS

But snet already has my identity, so I wonder if it should be sufficient to just do:

> snet organization create joel

I'm also unclear who the owner of the organisation is if I specify a different address. Since I'm making the transaction, am I automatically the owner? Or is that role granted upon the initial members?

If I'm automatically the owner, then I think having an empty member list should be possible.

**Comment by arturgontijo** [comment]
Yeah, the owner is the user that creates the organization.
Looking at [Registry.sol](https://github.com/singnet/platform-contracts/blob/master/contracts/Registry.sol#L127) I saw that's possible to create an organization without any "extra" members (with only the owner).
I'll fix this.
